### ISSUE TITLE
Backup / Restore

### ISSUE THREAD

**Issue by jvaubourg** [YunoHost-Apps/rainloop_ynh#1]
Hi,

Would it be possible to add scripts for saving/restoring with YunoHost?

Thank you :).

PS: Thank you for this nice job!

**Comment by scith** [comment]
Hello,
Yes that would be wise... I hope to have more time to work again on the app soon (and migrate it to 2.4).
Also we haven't migrated the issues yet: https://github.com/YunoHostPlugins-Testing/rainloop_ynh/issues
I'll see to it

Thanks

**Comment by scith** [comment]
Need testers on https://github.com/YunoHost-Apps/rainloop_ynh/pull/11 for this issue
