### ISSUE TITLE
 yunohost app initdb est déprécié 

### ISSUE THREAD

**Issue by vcorreze** [YunoHost-Apps/rainloop_ynh#10]
à l'installation, moulinette dit 

> Attention : « yunohost app initdb » est déprécié et sera bientôt supprimé
> 
> ```
> Yunohost 2.4.2
> Moulinette 2.4.0.1
> ```

8<-----EN
On fresh install, moulinette says : 

> warning: yunohost app initdb is deprecated and will be deleted.

**Comment by scith** [comment]
Salut, peux-tu essayer mon fork 2.4 HTTPS://github.com/scith/rainloop_ynh ?

Je compte le mettre ici mais peu de monde l'a testé pour le moment
Merci

**Comment by vcorreze** [comment]
Je viens de faire un `yunohost app upgrade -u https://github.com/scith/rainloop_ynh rainloop` qui est passé sans problèmes. 

Je n'ai pas vraiment de moyen de tester une installation _a nu_ sans effacer/réinstaller, je préfère éviter...
merci,

**Comment by scith** [comment]
OK je vais faire un PR alors merci

**Comment by polytan02** [comment]
Faites attention que dans vos deux dépôts les versions de rainloop ne sont pas les même (apparemment ici on est en 1.09 et dans l'autre dépôt c'est en 1.10).
Je ne sais pas si cela change grand chose ?

Sur le site de rainloop ils indiquent que la dernière version est v1.10.3.151 (09.08.2016)
