### ISSUE TITLE
Download rainloop sources instead of including it in sources

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/rainloop_ynh#12]
Here : https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/scripts/upgrade#L22

Try to download the zip file directly from https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip.

If the download fails, fallback to the zip including it in sources.

**Comment by scith** [comment]
Done in my fork but I haven't merged it yet sorry...
I think I will merge although some stuff still needs to be improved

**Comment by nicofrand** [comment]
No problem, I only saw your fork after creating this issue and the next PR :$
