### ISSUE TITLE
Upgrade backup

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#14]
See https://github.com/YunoHost-Apps/rainloop_ynh/pull/11#pullrequestreview-15225494
Need to improve the backup before upgrade script

**Comment by polytan02** [comment]
The last commit should have solved the backup issue.
Perform an upgrade, then a backup, then a restore and it should work :)

**Comment by scith** [comment]
No for this issue I meant that the upgrade script should be improved because I'm not sure it is efficiently backuping the app at the start of the upgrade process (see the first lines)

**Comment by polytan02** [comment]
Have you retested it since the last commits ?

**Comment by polytan02** [comment]
I just noticed the sql database was dumped but not backuped, so I did a fix https://github.com/YunoHost-Apps/rainloop_ynh/commit/4b11920c0210cf149715f35ea2ad203951950720

I'm installaing a new vps to test the app further.

**Comment by polytan02** [comment]
So, it should be ok now, there was a weird conflict between dumps :/

I tried on my vps and it works ok for backup and restore

**Comment by polytan02** [comment]
@scith I let you test and update community.json once OK for you ?

**Comment by scith** [comment]
Are we both talking about https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/scripts/upgrade#L5-L15 ?

**Comment by polytan02** [comment]
I don't know.
Have you tried the app since the last commit ? On my side, everything works :)
