### ISSUE TITLE
YunoHost logo overlay hides the "expand" and "go to top" icons

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/rainloop_ynh#15]
A picture is worth a thousand words:

![ynh-rl](https://cloud.githubusercontent.com/assets/3419050/22793672/c84f43e6-eef0-11e6-928d-1311c01f1fa8.png)

**Comment by scith** [comment]
Arc SH**... They did this my tagspaces app as well, one update just brought stuff below the logo.
I'm not sure about what to do for this?

**Comment by nicofrand** [comment]
I actually have the issue with other apps (on the laverna app, the logo is displayed over the remoteStorage input).

I opened a ticket [here](https://dev.yunohost.org/issues/786).
