### ISSUE TITLE
remove fork

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#16]
This version is a fork of a fork of afork ... As a result it looses visibility in github.

How to transform it in a version of its own?

**Comment by M5oul** [comment]
You have to ask to GitHub to remove the fork line.

**Comment by polytan02** [comment]
I don't think we can do much on this aspect ? That's how github works I'm afraid :(

**Comment by scith** [comment]
I have asked them, let's see

**Comment by polytan02** [comment]
Which forks have you asked to remove ?
