### ISSUE TITLE
smtp : port ssl://465 or tcp://587 ? 

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/rainloop_ynh#18]
We had this discussion for z-push_ynh on jabber so as which port should we use to communicate with smtp ? 

For z-push_ynh, I initially looked at rainloop and use port 465.
However, the guys packaging roundcube told me that the "official" smtp port are 25 (clear) and 587 (encrypted).

For z-push_ynh, 465 was only working with ssl and 587 was only working with tcp/startssl.

I was also able to configure nextcloud to use port 587.

Should we also use port 587 in rainloop ?

**Comment by scith** [comment]
If it works with 587 and using 587 is better why not

**Comment by polytan02** [comment]
I did a commit and tested the new config, it works on my test server : https://github.com/YunoHost-Apps/rainloop_ynh/pull/20

**Comment by scith** [comment]
Thanks
