### ISSUE TITLE
Problème to access administration interface

### ISSUE THREAD

**Issue by Scaranaik** [YunoHost-Apps/rainloop_ynh#2]
I would like to change some configurations (like enabling third parties email addresses) 
but I can't reach https://product_installation_URL/?admin
as explained in  http://www.rainloop.net/docs/configuration/
I'm always back to https://product_installation_URL/app?

Is it a bug ? or there is another way to reach it ?

**Comment by scith** [comment]
Hi, I think you have to use https://product_installation_URL/app/?admin
Can you try this please?
Thanks

**Comment by Djip007** [comment]
for yunohost integration:
http://DOMAIN.TLD/rainloop/app/?admin
