### ISSUE TITLE
Issue when trying to connect to rainloop when username is different from email address

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/rainloop_ynh#24]
I have an issue with the following test case : 
- domain : domain.tld
- Username : john
- Email address : john.doe@domain.tld

When I connect to rainloop, it fails.
Then, if I enter "john/passwd) at the login screen it works but the email address on top right corner is john@domain.tld, which is not the one I entered during account creation via the YnH interface.

It works ok when I do all the above from roundcube.

**Comment by polytan02** [comment]
To be noted that I have the exact same issue with z-push which assumes that email == username.

**Comment by scith** [comment]
There is a plugin that is installed by default but not activated : ynh-login-mapping.
It was activated by default but I disabled it because it creates errors in the logs and is unnecessary for most users anyway...
Can you try to enable the plugin in the admin?

We should perhaps indicate this in the readme
I would not be in favor of enabling the plugin by default unless the use case is really widespread

**Comment by scith** [comment]
Does it work with the aforementioned plugin enabled?

**Comment by polytan02** [comment]
Sorry, I am not able to test in the close future.
Have you tried ?

**Comment by scith** [comment]
No worries. I am pretty sure it works because Djipp007 developed the plugin for this exact purpose.
As for me, I don't even host my emails on my yunohost... My main email address is set to an externally managed mailbox and rainloop does the connection automatically

**Comment by polytan02** [comment]
@scith I activate the `ynh-user-mapping` and it works for the login : "john" and email "john.doe@domain.tld". 

Should we activate this by default ? Where are the logs you mentionned ? (I would like to review them)

**Comment by scith** [comment]
To activate by default, replace: https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/scripts/install#L83 with
`plugins="auto-domain-grab,ynh-login-mapping"`

The errors are in /var/log/nginx/YOURDOMAIN-error.log

Here is mine when I activate the plugin
> 2017/03/05 15:27:59 [error] 8115#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  ldap_bind(): Unable to bind to server: Protocol error in /var/www/rainloop/app/data/_data_/_default_/plugins/ynh-login-mapping/index.php on line 27" while reading response header from upstream, client: 127.0.0.1, server: ynhvm.local, request: "GET /rainloop/app/index.php?sso&hash=XXX HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-rainloop.sock:", host: "ynhvm.local", referrer: "https://ynhvm.local/yunohost/sso/?r=XXX="

**Comment by scith** [comment]
There is something I don't get with this bug. We are already authenticating the users with their correct email address and not their usernames... https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/sources/sso/sso.php#L9

**Comment by scith** [comment]
I think I found the error in the log.
We need to add: `ldap_set_option($cnx, LDAP_OPT_PROTOCOL_VERSION, 3);` in the line 21: https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/sources/plugins/ynh-login-mapping/index.php#L21

Can you try to do this and see if the errors caused by this plugin disappear?
If yes, I can push the fix and activate the plugin by default

**Comment by polytan02** [comment]
I will try that

**Comment by polytan02** [comment]
So, with the previous version, I found the log.

Then, I changed with the code you offer and I can connect and I don't have any log anymore.

Are we OK to : 
1) activate this by default
2) activate it on the next upgrade

**Comment by scith** [comment]
I don't see why not.
See https://github.com/YunoHost-Apps/rainloop_ynh/commit/c38f23e72ea55fe5ac77fbf1caf535fb18253214 and https://github.com/YunoHost-Apps/rainloop_ynh/commit/07fb0d29ba36ee826ad8109d6126ddbcedfafa3f

One problem though: people who have installed rainloop with the new version will not have this plugin activated, as the upgrade procedure does not change the config (of course). But people in this case just have to activate the plugin in the admin area. The plugin fix will be pished by the upgrade anyway

**Comment by polytan02** [comment]
Thanks for having done it.
I was preparing a commit fot all of this, but you merge directly !
Let's go official now ;)
