### ISSUE TITLE
admin panel handled by ldap

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/rainloop_ynh#25]
Hi, 
it would be great if as many other apps, you could decide which user can be admin at the install and then connect through ldap when accessing
> domain.tld/rainloop/app/?admin

probably using $YNH_APP_ARG_ADMIN
https://github.com/YunoHost/example_ynh/blob/master/scripts/install#L21

Thanks

**Comment by polytan02** [comment]
This is a clever point.

**Comment by scith** [comment]
Unfortunately, we cannot do single sign-on (HTTP Auth) on the admin interface, at least not the way we do it for the main app.

In the initial version of the app we used to ask for an admin user. However, Rainloop forced us to put the user's password in clear text in the config file!!! As a result, we decided to switch to an admin password.

However, note that the admin password set during install is now stored in the app setting and can be retrieved with `sudo yunohost app settings rainloop password`

Sorry about that but I don't think there is a way to answer this feature request yet.

**Comment by polytan02** [comment]
Would it make sense to use the yunohost admin password for the rainloop admin panel ? It would make things easier ?

**Comment by scith** [comment]
Then the yunohost admin password would have to be put in clear text in the config file, even worse :crying_cat_face: 
I think that the current solution is the best we can do at this stage. Let's monitor Rainloop changelog and if any new feature arrives that would make this possible, we could reopen the issue then.
What do you think?

**Comment by polytan02** [comment]
Ok, I was not understanding that the admin password was put in clear. There is no way to protect it such as https://github.com/YunoHost-Apps/cops_ynh/blob/master/scripts/install#L118-L124 ?

**Comment by polytan02** [comment]
What is the limitation of rainloop for this password ? (I don't mean to be a pain, I know you did lot of work on this, I just want to unsderstand and have a track in this issue, for later)

**Comment by scith** [comment]
Can you check the application.INI config file of your rainloop install to see whether your admin password appears in clear in the field "admin_password" ?
I can't check mine now

Regarding SSO and http author, we do this using the API https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/sources/sso/sso.php

The rainloop api is under documented and as far as I know does not allow automatic login to the admin panel. Bug perhaps this can be "reversed engineered" some way... Let's try to inspect the source code to see whether this is possible

**Comment by mokas01** [comment]
if we talk about the file 
> /app/data/_data_/_default_/configs/application.ini

the password hashed in my install

and salted if I understand well line 100-102 of
>/app/libraries/RainLoop/Config/Application.php

**Comment by scith** [comment]
Cool! I suppose this is due to the fact that we now set the password with the API

However, if we set the admin as a specific user and the user changes his/her password then we cannot change it back in the admin panel (because the admin is not LDAP)

So do you think there is a way to improve the admin login given these constraints?
Thanks

**Comment by mokas01** [comment]
for info this has been required as well on rainloop github
https://github.com/RainLoop/rainloop-webmail/issues/1065

**Comment by polytan02** [comment]
@scith I agree with you, because the admin password is not linked to ldap, better leaving it like that so far.

For the future, maybe we could "upgrade" rainloop after each change of yunohost admin password change ? This is not possible today.
