### ISSUE TITLE
post_domain_add hook error

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/rainloop_ynh#26]
Hi, 

I just added a new domain, and i saw only 2 lines of error, which I hope will make sense to you : 
> Attention : cp: impossible d'évaluer « ../conf/data/domains/domain.tld.ini »: Aucun fichier ou dossier de ce type
> Erreur : Échec de l'exécution du script « /etc/yunohost/hooks.d/post_domain_add/50-rainloop »

if it does change anything, it was a subdomain to the main domain, and rainloop is also installed on another subdomain
i don't want to use this domain for rainloop anyway, but i thought you might want to be informed of the issue

**Comment by scith** [comment]
Thanks, we will investigate

**Comment by scith** [comment]
Fixed in https://github.com/YunoHost-Apps/rainloop_ynh/commit/8c857742f8f0f90b7c9f658ca1a8226b0e9eab9b
Thanks for reporting this

**Comment by mokas01** [comment]
guys you rock
