### ISSUE TITLE
redirection after sso login and weird url

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/rainloop_ynh#27]
Hi,

I installed rainloop at the root of a subdomain. I might have done something wrong, but here is what i have : 
i used the cli install, chose as domain : 
> mail.domain.tld

and as path : 
> /

(i should probably have left it blank ?)

- the url of rainloop is https://mail.domain.tld//app/ (with 2 / before app)
- After sso login, i am redirected to https://mail.domain.tld/app/ (with 1 / before app) —> i have to reload the url https://mail.domain.tld so it is redirected correctly

Is this behavior my mistake, or a bug in cli install ? Could the app after sso be redirected to mail.domain.tld and let rainloop redirect to the correct path ?

Thanks again for all the good work done on this app!

**Comment by scith** [comment]
Hi, it seems like a bug indeed. The path is not corrected properly. I'll look into it
Thanks

**Comment by scith** [comment]
However the /app after is unfortunately needed because of the way rainloop handles SSO. Rainloop is under /app and the root handles the SSO

**Comment by scith** [comment]
Fixed :)

**Comment by scith** [comment]
Hi think you just have to upgrade the package to fix the bug

**Comment by mokas01** [comment]
It is fixed and working \o/
Thanks again for the work you provide on this package !
It is great to get things improved and fixed that quickly with nice explanations and support ! Please keep going that good !
