### ISSUE TITLE
Login users with LDAP

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#29]
Hello
@Djip007 do you think you can extend your login_mapping plugin to authenticate users with LDAP ?
This way we could perhaps remove the clear password used in this hack: https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/sources/sso/sso.php

Thanks

**Comment by Djip007** [comment]
heu ca fait longtemps que j'ai pas eu le temps de regarder
login_mapping utilise deja la LDAP... et n'utilise que le mail pas le password pour recuperer l'utilisateur...
Du coup pour le sso.php le mdp peut etre mis avec n'import quoi... 
par contre il ne passe pas en claire, il est crypté dans le $ssoHash le $password ne quitte pas le serveur...

**Comment by alexAubin** [comment]
Super old issue, probably not relevant anymore, closing ...
