### ISSUE TITLE
Config everything with PHP instead of sed

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#3]
Replace
https://github.com/YunoHostPlugins-Testing/rainloop_ynh/blob/master/scripts/install#L73-L78

With PHP only config. Perhaps with: https://github.com/RainLoop/rainloop-webmail/blob/34a9b8cbc5f28c229721dac1fb9453cccce1b5e7/rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php#L3485-L3529

Something like?

``` php
<?php

$_ENV['RAINLOOP_INCLUDE_AS_API'] = true;
include '<path-to-rainloop-folder>/index.php';

$sParamName = 'MYSQLUSER';
$sConfigSector = 'contacts';
$sConfigName = 'pdo_user';

$oConfig = \RainLoop\Api::Config();
echo \RainLoop\Api::Actions()->setConfigFromParams($oConfig, $sParamName, $sConfigSector, $sConfigName) ? 'Done' : 'Error';

?>
```

**Comment by alexAubin** [comment]
Super old issue, probably not relevant anymore, closing ...
