### ISSUE TITLE
Pgpback don't work

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/rainloop_ynh#30]
The pgpback plugin don't work

When the keys are saved in the server and I tried to access in an other computer No data found. Keys not set.

Pgpback is not compatible with the last release of rainloop ?

**Comment by scith** [comment]
Hi
What files do you have in /var/WWW/rainloop/pgpback ?
Thanks

**Comment by Rafi594** [comment]
fav.php index.html and lib

**Comment by scith** [comment]
OK I found the problem
In /var/www/rainloop/pgpback you must create the folder "keys":
``` bash
mkdir /var/www/rainloop/pgpback/keys
chown -R www-data: /var/www/rainloop/pgpback/keys
```

Tell me if this works and I will fix the issue by commit

**Comment by Rafi594** [comment]
This modification works fine I will create a PR

**Comment by scith** [comment]
Thanks for noticing the issue
I found an easier way to fix by creating the keys subdirectory in the sources.
https://github.com/YunoHost-Apps/rainloop_ynh/commit/e59caac30ed554960af261728faaf46a52a40730
