### ISSUE TITLE
Error on installation, but installs after other apps were installed

### ISSUE THREAD

**Issue by p3k** [YunoHost-Apps/rainloop_ynh#32]
On a fresh install of YH on an Odroid C1 I got an error when installing Rainloop:

```
<p>[302] The following PHP extensions are not available in your PHP configuration!</p>
<ul><li>cURL</li></ul>+ EXIT_PROPERLY
+ exit_code=46
+ '[' 46 -eq 0 ']'
+ trap '' EXIT
+ set +eu
+ echo -e '\e[91m \e[1m'
+ echo -e '!!\n  rainloop install'\''s script has encountered an error. Installation was cancelled.\n!!'
```

I installed some other apps (Kanboard, Nextcloud and OpenSondage IIRC) and tried again to file this issue report when installation surprisingly succeeded. Thus, I assume one of the other apps installed the cURL PHP extension…?

**Comment by alexAubin** [comment]
Super old issue, probably not relevant anymore, closing ...
