### ISSUE TITLE
Special characters not allowed in password ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/rainloop_ynh#33]
To be seen in that's specific to rainloop or not, but someone reported on the forum that he could not use special characters in the admin password (e.g. `}`)

https://forum.yunohost.org/t/rainloop-installation-fails/3317

To be investigated... Maybe that's just some missing quotes in bash where the variable is used.

**Comment by maniackcrudelis** [comment]
It's a global problem with sed, even if you use quotes, some characters are interpreted because they're a part of sed syntax.
It's a problem with our sed helper, we have to escape all this characters.

**Comment by alexAubin** [comment]
To be handled by the core someday ...
