### ISSUE TITLE
How to integrate this with sso

### ISSUE THREAD

**Issue by mehrdad-shokri** [YunoHost-Apps/rainloop_ynh#39]
Would you please provide an example or code snippet on how to integrate rainloop with an external sso service (like cas).  Thank you.

**Comment by mehrdad-shokri** [comment]
@scith can help please?

**Comment by scith** [comment]
Hello, what do you mean? Rainloop only logs account on email servers. If your external email server like domain.TLD uses cas to log users in, it does not make a difference to rainloop. Rainloop will be able to log in.

What you need to get is your email server SMTP and POP/IMAP address.
Then go to your rainloop domain.TLD/rainlooppath/?admin and log in. There you will be able to add new domains with custom settings (IMAP/pop/SMTP address, mode of login: username only or email address, etc...)
