### ISSUE TITLE
Manage users via Hooks

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#4]
When an user is added:
- Autoconfigure the sync address book (Baikal or Owncloud)
- Add alternative emails

When an user is deleted:
- Remove the user's folders

For synced address books, perhaps see: https://github.com/RainLoop/rainloop-webmail/blob/34a9b8cbc5f28c229721dac1fb9453cccce1b5e7/rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php#L6508-L6538

Remove user's folder, perhaps with:

``` php
define('RAINLOOP_INCLUDE_AS_API', true);
include '/var/www/rainloop/index.php';
\RainLoop\Api::ClearUserData('user@yourdomain.com');
```

Or delete the folder

**Comment by scith** [comment]
Not working yet. Here is my hook that does not work yet (post_user_delete)

``` bash
#!/bin/bash

app='rainloop'	# This could never work with multi-instance. Need to find a better way
user=$1
rainloop_path=/var/www/$app/app

# Loop through all email aliases for this user and delete the associated Rainloop users
	allaliases=`ldapsearch -LLL -x -b uid=${user},ou=users,dc=yunohost,dc=org mail | grep -v "dn:" | sed "s/mail: //" `
	for alias in $allaliases ; do
		sudo php -r "define('RAINLOOP_INCLUDE_AS_API', true); include '${rainloop_path}/index.php'; \RainLoop\Api::ClearUserData('${alias}');" >/dev/null
	done
```

**Comment by alexAubin** [comment]
Super old issue, probably not relevant anymore, closing ...
