### ISSUE TITLE
Problème identité d'envoi de mail - serveur avec plusieurs noms de domaine

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/rainloop_ynh#43]
J'utilise rarement rainloop, et en voulant envoyer un mail aujourd'hui, ça n'a pas marché : "envoi impossible". J'ai plusieurs domaines sur mon serveur, et celui de mon adresse mail n'est pas le domaine par défaut, et du coup pas celui du smtp.
Du coup comme mail d'envoi il mettait : tom@domaine1.truc. J'ai dû ajouter une identité avec tom@domaine2.truc, et la mettre par défaut, et les envois avec cette identité marche.
Est-ce qu'il serait possible que ça se configure automatiquement à l'installation de rainloop, et à la création des users ? Que le mail d'envoi soit directement le bon.

**Comment by Christophe31** [comment]
En effet ce bug m'affecte aussi. (Il ne semble toujours pas résolu).
