### ISSUE TITLE
Unable to set username different from mail adress

### ISSUE THREAD

**Issue by ax-meyer** [YunoHost-Apps/rainloop_ynh#44]
Sometimes mail accounts require a different username than the e-mail address for login, e.g. for us it is ab123456@domain.com for login, but the mail address is actually firstname.lastname@domain.com.

It would thus be great if an option for a differing username would be added for accounts. I tried custom mapping, but a) it does not seem to work and b) it is not practical if the user cannot set it themselves.

Otherwise a great tool, but as long as this is missing, we cannot use it here.

Keep the good work up!

**Comment by laquiche-secu** [comment]
It's a probleme for me | c'est aussi un problème pour moi

**Comment by Jaxom99** [comment]
I think it's rather an issue on the rainloop side, not due to the packaging into yunohost. Did you search over there, on their repo ?
