### ISSUE TITLE
Rainloop SMTP settings no longer work

### ISSUE THREAD

**Issue by matlag** [YunoHost-Apps/rainloop_ynh#45]
I upgraded to Yunohost 3.0.
Previous SMTP default settings was to use SSL on port 465.
Yunohost 3.0 no longer allows that, you need STARTTLS and port 587.

Therefore, current Rainloop's version does not allow sending emails!

EDIT: Well, default.ini is on SSL/465, domain.tld.ini is on TLS/587. I don't know which one is used for what.
So maybe it's what it should be, but I do have a problem sending out emails, and only on Rainloop, I can send emails using Nextcloud/Mail and K9.

**Comment by JimboJoe** [comment]
The application hasn't been changed since YunoHost 3.0, so there's a good chance you spotted a problem in there!
How about trying the different combinations, setting the `smtp_secure` option to `STARTTLS`, starting the with the `domain.tld.ini` file (most probable case)?

**Comment by matlag** [comment]
I just tried again, and no success. Here's my current domains.tld.ini (just replaced TLS with STARTTLS in smtp_secure field

imap_host = "localhost"
imap_port = 993
imap_secure = "SSL"
imap_short_login = On
sieve_use = On
sieve_allow_raw = On
sieve_host = "localhost"
sieve_port = 4190
sieve_secure = "TLS"
smtp_host = "localhost"
smtp_port = 587
smtp_secure = "STARTTLS"
smtp_short_login = On
smtp_auth = On
smtp_php_mail = Off
white_list = ""

**Comment by JimboJoe** [comment]
Did you change the configuration in the ini file corresponding to your domain in `/var/www/rainloop/app/data/_data_/_default_/domains/`?

**Comment by matlag** [comment]
/me goes hide behind the curtain for 1h then come out...

Sooooooo, my real config file was indeed on SSL on port 465.
I changed it for STARTTLS on 587.

Now, i don't get the same error message, I get "authentication failed".
I tried using smtp_short_login on "Off" and "On", same result.

But I would say that's a progress...

I also tried to "just" copy-paste the latest domain.tld.ini (copied above). There are differences in sieve settings, but not so much anything else on the smtp part. Of course, same result: "Authentication failed" (translated from French).

**Comment by JimboJoe** [comment]
Maybe some interesting logs in `/var/log/mail.log` and `/var/www/rainloop/app/data/_data_/_default_/logs`... ?

**Comment by matlag** [comment]
/var/log/mail.log (replaced my hostname by 'hostname' and user name by "myself", just in case

Jul 31 20:55:58 hostname dovecot: imap-login: Login: user=<myself>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=14902, TLS, session=<PdReKFVydph/AAAB>
Jul 31 20:55:58 hostname postfix/submission/smtpd[14889]: connect from localhost.localdomain[127.0.0.1]
Jul 31 20:55:58 hostname postfix/submission/smtpd[14889]: disconnect from localhost.localdomain[127.0.0.1] ehlo=1 quit=1 commands=2
Jul 31 20:55:58 hostname dovecot: imap(myself): Logged out in=11 out=416
Jul 31 20:55:59 hostname dovecot: imap-login: Login: user=<myself>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=14904, TLS, session=<ZMVmKFVyfJh/AAAB>
Jul 31 20:55:59 hostname dovecot: imap(myself): Logged out in=566 out=6252

The rainloop app log is totally empty.

**Comment by matlag** [comment]
SOLUTION:
I actually removed and re-installed the package and now it works!

Now, the difference with my previous config file is I had set
My hand-changed config file:
smtp_secure = "STARTTLS"

and now I see that the default config file has 
smtp_secure = "TLS"

So I assume that was it!
We can close this.
