### ISSUE TITLE
Installation Fails during 'Configuring Rainloop' stage

### ISSUE THREAD

**Issue by wayneoutthere** [YunoHost-Apps/rainloop_ynh#58]
Good day,
I am not very good at being able to extract log files (working on it) but I wanted to send this right away because there are others who are confirming this bug.

During installation process, in the 'configuring rainloop' stage, it gets stuck and does not proceed to successful installation.  

Another user in the group confirmed this.  I will try to reply to this with my error logs if I can figure out how to get them out of the server...

**Comment by bhdouglass** [comment]
I'm getting this as well, after waiting about 15 minutes I killed the process and removed rainloop. Attached is my log: 
[20190709-135543-app_install-rainloop.log](https://github.com/YunoHost-Apps/rainloop_ynh/files/3373525/20190709-135543-app_install-rainloop.log)

**Comment by InspireToCode** [comment]
Same, rebooting server was only way for me to stop the install and gain access to admin area again.
Logs:. https://paste.godhub.xyz/kurovoriti.sql

**Comment by wayneoutthere** [comment]
here is my log:
[20190709-132225-app_install-rainloop.log](https://github.com/YunoHost-Apps/rainloop_ynh/files/3373571/20190709-132225-app_install-rainloop.log)

**Comment by maniackcrudelis** [comment]
Your timezone fails the install script. We didn't noticed that before because our CI servers are on UTC+2.
We'll try to fix that as quickly as possible !

**Comment by maniackcrudelis** [comment]
You should be able to install rainloop now from this PR, https://github.com/YunoHost-Apps/rainloop_ynh/pull/59.

```
sudo yunohost app install https://github.com/YunoHost-Apps/rainloop_ynh/tree/fix_getopts
```
Please tell me if it fails again to install.

**Comment by InspireToCode** [comment]
This PR worked for me and I was able to install

**Comment by InspireToCode** [comment]
> You should be able to install rainloop now from this PR, #59.
> 
> ```
> sudo yunohost app install https://github.com/YunoHost-Apps/rainloop_ynh/tree/fix_getopts
> ```
> 
> Please tell me if it fails again to install.

Alright, have some testing I was able to notice that the app failed after trying to sign into an account but FAILING to sign in multiple times in a row, in which would take the entire Yunohost down to produce 503 errors everywhere. Solution to fix this is uninstalling Rainloop.

**Comment by bhdouglass** [comment]
Installing form that PR works for me, thanks for the quick response!

**Comment by maniackcrudelis** [comment]
@D347HxD I have the same kind of issue with my rainloop, when signing in into an external account, rainloop often crashes.
Didn't dig up into the log, it usually works after some try.
That's probably anyway an issue on rainloop part.

**Comment by InspireToCode** [comment]
@maniackcrudelis

> @D347HxD I have the same kind of issue with my rainloop, when signing in into an external account, rainloop often crashes.
> Didn't dig up into the log, it usually works after some try.
> That's probably anyway an issue on rainloop part.

Strange. That will be my main case though, I was hoping to use Rainloop with external emails (gmail, other domains, etc) so I can browse my emails all from one location. 

What do you mean by it usually works after some tries? Do you mean after reinstalling it a few times it should allow for users to use it okay?

And lastly, I plan to allow my family to use this. Not all are tech savvy and I estimate some will type their emails in wrong a few times at the start. It seems if they do this, it'll take my server down into a 503 (as it takes the entire Yunohost to 503, not just mailoop). 

I havent installed Rainloop from source ever, but I imagine something like this would be caught by now if it's their end, I am going to look for an issue in thier github so we can keep track of this.

**Comment by maniackcrudelis** [comment]
What I meant was when I try to load an external email address Rainloop often crashes, my tab closes on Firefox. I have to retry 3 or 4 times before rainloop actually load its interface and show me my emails.
It doesn't happen with my main address on my server.

However, my YunoHost isn't affected by the crash of Rainloop, as far as I know.

**Comment by wayneoutthere** [comment]
I got it working with `sudo yunohost app install https://github.com/YunoHost-Apps/rainloop_ynh/tree/fix_getopts`  but had to first learn how to remove the failed one with `sudo yunohost app remove rainloop`

Learned that command line stuff in Yunohost is pretty great! Just leaving this in case someone else like me doesn't even know how to install a PR to test! :)
