### ISSUE TITLE
OpenPGP keys are lost after cookie deletion... 

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#6]
So when cookie are cleared, the openPGP keys are gone... This is absurd.
I think we should try to incorporate xof's customisation: https://github.com/chtixof/pgpback_ynh
See https://forum.yunohost.org/t/pgp-encryption-for-roundcube-or-other-e-mail-client/361/8

Perhaps newer versions correct this problem? I will have a look

**Comment by Djip007** [comment]
cf: https://github.com/RainLoop/rainloop-webmail/issues/349
this is unsafe to have it server side... and may be not realy safe in browser side ...

**Comment by jcgruenhage** [comment]
why is it unsafe to have them server side? they are encrypted with a passphrase after all

**Comment by scith** [comment]
Need testers on https://github.com/YunoHost-Apps/rainloop_ynh/pull/11 for this issue
