### ISSUE TITLE
Logout not clearing SSO

### ISSUE THREAD

**Issue by D3coded** [YunoHost-Apps/rainloop_ynh#64]
When logging out of rainloop im being correctly redirected to the login page.
But the problem here is, that when I enter the url in the browser again, I get logged in by the ynh sso automatically.

Why doesn't the logout button in rainlopp delete sso cookies?

**Comment by eauchat** [comment]
I can confirm this issue. Logging out from the rainloop interface redirects the user to the rainloop login page, but
 - if you visit another service or the sso you will still be logged in,
 - if you reload the rainloop page you're still logged in and emails are still visible.
