### ISSUE TITLE
Php extension missing

### ISSUE THREAD

**Issue by Taekiro** [YunoHost-Apps/rainloop_ynh#66]
Hi,
I had an issue while installing rainloop, I got an error message telling me that the _dom_ php extension was missing. I don't know if _php-xml_ is supposed to be installed by default with YunoHost (and I would have removed it for some reason), but it would be a good idea to add a dependency to this package or to check for it in the install process.
Best regards,
Taekiro

**Comment by ericgaspar** [comment]
Should be solved with #68
