### ISSUE TITLE
Download source zip

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#7]
See https://github.com/YunoHostPlugins-Testing/rainloop_ynh/issues/18#issuecomment-221972805
https://repository.rainloop.net/v2/webmail/rainloop-latest.zip

**Comment by scith** [comment]
See

> OK find the versioned version... info ca be found here:
> http://repository.rainloop.net/v2/core.open.json
> 
> find info here ;)
> https://github.com/freebsd/freebsd-ports/blob/master/mail/rainloop/Makefile
> 
> we can use history of this file to have older release...

**Comment by Djip007** [comment]
last version here:
https://github.com/RainLoop/rainloop-webmail/releases

**Comment by Djip007** [comment]
if possible use PGP public key (http://repository.rainloop.net/RainLoop.asc) to test download 
...

**Comment by scith** [comment]
Need testers on https://github.com/YunoHost-Apps/rainloop_ynh/pull/11 for this issue
