### ISSUE TITLE
Add logrotate for all logs

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/rainloop_ynh#70]
Hi,

I sometimes need to add some logs to debug a failing connection etc. and therefore edit the line 163 of `/var/www/rainloop/app/data/_data_/_default_/configs/application.ini`.
Those logs can be quite heavy and take a lot of place on a disk.

The files are stored in `/var/www/rainloop/app/data/_data_/_default_/logs` with a name like `log-2020-10-20.txt`.

Could we add the following rule to the logrotate please?

```
/var/www/rainloop/app/data/_data_/_default_/logs/*.txt {
        # Rotate if the logfile exceeds 100Mo
    size 100M
        # Keep 12 old log maximum
    rotate 12
        # Compress the logs with gzip
    compress
        # Compress the log at the next cycle. So keep always 2 non compressed logs
    delaycompress
        # Copy and truncate the log to allow to continue write on it. Instead of move the log.
    copytruncate
        # Do not do an error if the log is missing
    missingok
        # Not rotate if the log is empty
    notifempty
        # Keep old logs in the same dir
    noolddir

}
```

If you wish I can make a merge request for that.

**Comment by tituspijean** [comment]
This would be implementable by adding `ynh_use_logrotate --logfile=$final_path/app/data/_data_/_default_/logs` around this line: https://github.com/YunoHost-Apps/rainloop_ynh/blob/ca7728631c4ade665fd857a2d15308088d182e4d/scripts/install#L180
(and corresponding lines in other scripts)
