### ISSUE TITLE
Upgrade fails with dependencies conflict

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/rainloop_ynh#71]
Hi there,

On my small VPS, install went well :ok_hand:  but upgrade recently failed :crying_cat_face:  . It seems to be a dependecies conflict in php versions. Is there something you can do to help ? 

The relevant log is here : https://paste.yunohost.org/raw/isakoropak

No emergency at all, as maybe it's not even due to the package but to my setup. Thanks a lot for your advices !

**Comment by kay0u** [comment]
Hi!

I think there is still a bug with sury (so on our side). The best way for you to fix the issue is to upgrade from stretch to buster :-)
