### ISSUE TITLE
YunoHost 2.4

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#8]
See https://forum.yunohost.org/t/news-about-app-management-and-packaging-in-yunohost-2-4/1379

**Comment by Djip007** [comment]
y a un peu de boulot...

**Comment by scith** [comment]
Hello @Djip007 @M5oul @jeromelebleu @maniackcrudelis @mbugeia 
I have updated the package in my fork: https://github.com/scith/rainloop_ynh
- Update to 2.4
- Backup and restore script
- Download source zip 1.10.1.127 (but no checksum: how to do that?)
- Add Sieve filters support

Could you please test it and tell me if I can PR?

Thanks

**Comment by maniackcrudelis** [comment]
Pour tester la somme de contrôle, tu peux jeter un coup d'oeil là:
https://github.com/maniackcrudelis/leed_ynh/blob/master/scripts/.fonctions#L83-L84

**Comment by scith** [comment]
Hm merci mais on dirait que c'est avec GPG ? https://github.com/RainLoop/rainloop-webmail/releases
Fichier .asc
Je vais me renseigner

**Comment by maniackcrudelis** [comment]
Personnellement je calcule les sommes de contrôle moi même et je les stocke pour être sûr que l'intégrité du fichier n'est pas modifiée entre la release du package et l'installation.

**Comment by jeromelebleu** [comment]
Pour la somme de contrôle, si tu veux le faire directement dans ton script sans passer par un fichier en plus : https://github.com/YunoHost-Apps/roundcube_ynh/blob/master/scripts/_common.sh#L33-L34
Pour vérifier la signature avec GPG, c'est un peu plus long et gourmand (nécessite le paquet `gnupg`, d'importer la clé de Rainloop, et de vérifier l'archive...). Mais c'est un sujet qu'on pourrait discuter, dans « les bonnes pratiques »...

**Comment by M5oul** [comment]
Install fail, with an error to connect to MySQL database:

``` fish
+ dbuser=rainloop
+ dbname=rainloop
++ ynh_string_random
++ sed -n 's/\(.\{24\}\).*/\1/p'
++ tr -c -d '[A-Za-z0-9]'
++ dd if=/dev/urandom bs=1 count=200
+ dbpass=VI8sOjeQ5k7UJFSMfnBiovOr
+ ynh_mysql_create_db rainloop rainloop VI8sOjeQ5k7UJFSMfnBiovOr
+ db=rainloop
+ sql='CREATE DATABASE rainloop;'
+ [[ 3 -gt 1 ]]
+ sql+=' GRANT ALL PRIVILEGES ON rainloop.* TO '\''rainloop'\''@'\''localhost'\'''
+ [[ -n VI8sOjeQ5k7UJFSMfnBiovOr ]]
+ sql+=' IDENTIFIED BY '\''VI8sOjeQ5k7UJFSMfnBiovOr'\'''
+ sql+=' WITH GRANT OPTION;'
+ ynh_mysql_execute_as_root 'CREATE DATABASE rainloop; GRANT ALL PRIVILEGES ON rainloop.* TO '\''rainloop'\''@'\''localhost'\'' IDENTIFIED BY '\''VI8sOjeQ5k7UJFSMfnBiovOr'\'' WITH GRANT OPTION;'
++ sudo cat /etc/yunohost/mysql
+ ynh_mysql_connect_as root 'x0Dv[mfogJ' ''
+ mysql -u root '--password=x0Dv[mfogJ' -B ''
Warning: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
Executing script '/var/cache/yunohost/from_file/rainloop_ynh-master/scripts/remove'...
+ set -eu
+ app=rainloop
```

The issue could come from an other problem.

**Comment by scith** [comment]
@Moul I can't reproduce your problems. Have you used https://github.com/scith/rainloop_ynh?

**Comment by M5oul** [comment]
Yep, I used your repository. There is a problem in the database I use. It's not related to Rainloop.

> ‎[17:40:38] ‎Bram‎: pour railoop c'est mysql qui tourne pas

**Comment by scith** [comment]
Need testers on https://github.com/YunoHost-Apps/rainloop_ynh/pull/11 for this issue
