### ISSUE TITLE
Official app

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/rainloop_ynh#9]
Make Rainloop official? https://github.com/yunohost/apps#how-to-propose-your-app-to-be-integrated-in-the-official-applications-list

**Comment by Frereneo** [comment]
Hi,
Yes can you ensure that your work is reconciled in the YNH software repositories?
It's a shame as it works great!
Thank you for your work !!
Best regard

**Comment by polytan02** [comment]
Where are we on making this app official ? Is Jenkins/package_check green light ?

**Comment by scith** [comment]
No the check process must be improved but I didn't have time to test it further

**Comment by polytan02** [comment]
@maniackcrudelis Hi, we have performed some serious bugdix and cleaning.
We now have a green light on jenkins ! Yeah !
https://ci-apps.yunohost.org/jenkins/job/rainloop%20(Community)/

Do you see anything else which would prevent this app to become official ?

We still have this pull request https://github.com/YunoHost-Apps/rainloop_ynh/pull/20 to decide on or not. roundcube_ynh is using 587 too : 
[Roundcube_ynh config.inc.php using port 587](https://github.com/YunoHost-Apps/roundcube_ynh/blob/f5eb4d27a14e403080306de2334cfa20784dc48f/conf/config.inc.php#L61-L63)

**Comment by maniackcrudelis** [comment]
hello guys

So, regarding the port, 587 or 465, really I don't know !

Concerning to become an official app, I suggest to open a PR on the official list. Like that, we can discuss about that.
And, it's important to know it's not only my decision.
But, open a PR, and we'll discuss around that and check the whole code.

**Comment by polytan02** [comment]
- [x] Use of helpers to create the carddav database
- [x] See if we can make the app multi instances

**Comment by polytan02** [comment]
See this pull request :  https://github.com/YunoHost/apps/pull/155#partial-pull-merging

**Comment by polytan02** [comment]
Oh yes :)
