### ISSUE TITLE
Upstream is unmaintained, Rainloop shouldn't be a High Quality App

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/rainloop_ynh#91]
Rainloop in [not maintained anymore](https://github.com/RainLoop/rainloop-webmail/issues/2162) and this app is flagged as HQ.

![image](https://user-images.githubusercontent.com/36127788/169030547-87c7235c-57e0-49c4-a90d-32376b93030e.png)

The app shouldn't be flagged as High Quality.

[Snappymail](https://github.com/YunoHost-Apps/snappymail_ynh) can be installed as a remplacement.

**Comment by kescherCode** [comment]
I'd say SnappyMail should be listed *instead of* RainLoop as well.
